<template>
<a-layout id="components-layout-demo-fixed-sider">
  <a-layout-sider class="left">
    <div class="logo">Logo</div>
    <Menu class="menu" />
  </a-layout-sider>
  <a-layout :style="{ marginLeft: '200px' }">
    <a-layout-header :style="{ background: '#fff', padding: 0 }" />
    <a-layout-content :style="{ margin: '24px 16px 0', overflow: 'initial' }">
      <div :style="{ padding: '24px', background: '#fff', textAlign: 'center' }">
        ...
        <br />Really
        <br />...
        <br />...
        <br />...
        <br />long
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />content
      </div>
    </a-layout-content>
    <a-layout-footer :style="{ textAlign: 'center' }">Ant Design ©2018 Created by Ant UED</a-layout-footer>
  </a-layout>
</a-layout>
</template>

<script>
import Menu from "./menu";
export default {
  data() {
    return {
      selectedKeys: ["4"],
    };
  },
  components: {
    Menu,
  },
};
</script>

<style lang="stylus">
.left {
  position fixed !important;
  top: 0;
  left: 0;
  bottom: 0;
  display: flex;
  flex-direction: column;

  .logo {}

  .menu {
    flex: 1;
    background: #001529;
    overflow-y: auto;
  }
}

#components-layout-demo-fixed-sider .logo {
  // height: 32px;
  // background: rgba(255, 255, 255, 0.2);
  padding: 16px;
  background: red;
  color: #FFFFFF;
}
</style>
